// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk-sd-XR5Tff9hKQG77pGFe6mJK4OQJyQ',
    appId: '1:197026867712:web:f72c569c30db734ca186e5',
    messagingSenderId: '197026867712',
    projectId: 'ai-gernator-outfits',
    authDomain: 'ai-gernator-outfits.firebaseapp.com',
    storageBucket: 'ai-gernator-outfits.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8j75oQQi4tDW0cP1mUOu_27A9Z2id0Uc',
    appId: '1:197026867712:android:720acb7e95801a09a186e5',
    messagingSenderId: '197026867712',
    projectId: 'ai-gernator-outfits',
    storageBucket: 'ai-gernator-outfits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNjwi3CnMplK3VwaGDfHYo1568-TdB1us',
    appId: '1:197026867712:ios:7dcff37b16856098a186e5',
    messagingSenderId: '197026867712',
    projectId: 'ai-gernator-outfits',
    storageBucket: 'ai-gernator-outfits.firebasestorage.app',
    iosBundleId: 'Aigernatoroutfits.com.aiGernatorOutfits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNjwi3CnMplK3VwaGDfHYo1568-TdB1us',
    appId: '1:197026867712:ios:7dcff37b16856098a186e5',
    messagingSenderId: '197026867712',
    projectId: 'ai-gernator-outfits',
    storageBucket: 'ai-gernator-outfits.firebasestorage.app',
    iosBundleId: 'Aigernatoroutfits.com.aiGernatorOutfits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk-sd-XR5Tff9hKQG77pGFe6mJK4OQJyQ',
    appId: '1:197026867712:web:31e1b058c2a2fa95a186e5',
    messagingSenderId: '197026867712',
    projectId: 'ai-gernator-outfits',
    authDomain: 'ai-gernator-outfits.firebaseapp.com',
    storageBucket: 'ai-gernator-outfits.firebasestorage.app',
  );

}